apiVersion: apps/v1
kind: Deployment
metadata:
    name: students-deployment
    labels:
        app: students
spec:
    replicas: 1
    # replicas: 3
    selector:
        matchLabels:
            app: students
    template:
        metadata:
            labels:
                app: students
        spec:
            containers:
                - name: students
                  # image: aybjax/students:nocache-v1
                  image: aybjax/students
                  ports:
                      - containerPort: 8000
                      - containerPort: 50051
                  env:
                      - name: NATS_URL
                        valueFrom:
                            configMapKeyRef:
                                name: nats-config
                                key: nats-url
                      - name: NATS_PORT
                        value: '4222'
                      - name: REDIS_URL
                        valueFrom:
                            configMapKeyRef:
                                name: redis-config
                                key: redis-url
                      - name: REDIS_PORT
                        value: '6379'
                      - name: POSTGRES_DB
                        value: nis
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: postgres-user
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: postgres-secret
                                key: postgres-password
                      - name: POSTGRES_URL
                        valueFrom:
                            configMapKeyRef:
                                name: postgres-config
                                key: postgres-url
                      - name: POSTGRES_PORT
                        value: '5432'
                      - name: GRPC_COURSE_URL
                        valueFrom:
                            configMapKeyRef:
                                name: students-config
                                key: courses-url
                      - name: GRPC_COURSE_PORT
                        value: '50051'

---
apiVersion: v1
kind: Service
metadata:
    name: students-service
    annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8000'
spec:
    # type: NodePort
    selector:
        app: students
    ports:
        - name: http
          protocol: TCP
          port: 8000
          targetPort: 8000
          # nodePort: 30080
        - name: grpc
          protocol: TCP
          port: 50051
          targetPort: 50051
