version: '3.8'
services:
  # kong:
  #   image: kong
  #   volumes:
  #     - ./kong:/config
  #   environment:
  #     - KONG_DATABASE=off
  #     - KONG_DECLARATIVE_CONFIG=/config/kong.yml
  #     - KONG_PROXY_ACCESS_LOG=/dev/stdout
  #     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
  #     - KONG_PROXY_ERROR_LOG=/dev/stderr
  #     - KONG_ADMIN_ERROR_LOG=/dev/stderr
  #     - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
  #     - KONG_LOG_LEVEL=debug
  #     - KONG_PLUGINS=bundled
  #   ports:
  #     - "8000:8000/tcp"
  #     - "8001:8001/tcp"
  #     - "8443:8443/tcp"
  #     - "8444:8444/tcp"
  #   command: "kong start"
  #   depends_on:
  #     - courses
  #     - students
  #   networks:
  #     - ntw

  # courses:
  #   build: ./courses
  #   image: aybjax-courses
  #   container_name: aybjax-courses
  #   environment:
  #     - REDIS_URL=redis
  #     - REDIS_PORT=6379
  #     - NATS_URL=nats
  #     - NATS_PORT=4222
  #     - MONGO_USER=
  #     - MONGO_PASSWORD=
  #     - MONGO_URL=mongo
  #     - MONGO_PORT=27017
  #     - GRPC_STUDENT_URL=localhost
  #     - GRPC_STUDENT_PORT=50051
  #   depends_on:
  #     - initializer
  #   ports:
  #     - 666:8000
  #     - 50052:50051
  #   networks:
  #     - ntw

  # students:
  #   build: ./students
  #   hostname: students
  #   image: aybjax-students
  #   container_name: aybjax-students
  #   environment:
  #     - REDIS_URL=redis
  #     - REDIS_PORT=6379
  #     - NATS_URL=nats
  #     - NATS_PORT=4222
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_URL=postgres
  #     - POSTGRES_PORT=5432
  #     - POSTGRES_DB=nis
  #     - GRPC_COURSE_URL=localhost
  #     - GRPC_COURSE_PORT=50052
  #   depends_on:
  #     - initializer
  #   ports:
  #     - 667:8000
  #     - 50051:50051
  #   networks:
  #     - ntw

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: db
    networks:
      - ntw

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8888:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=root
    depends_on:
      - mongo
    networks:
      - ntw

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nis
    networks:
      - ntw

  adminer:
    image: adminer
    restart: always
    ports:
      - 8889:8080
    depends_on:
      - postgres
    networks:
      - ntw

  nats:
    image: nats:2.9.16-scratch
    restart: always
    command: [ "-js" ]
    ports:
      - "4222:4222"
    networks:
      - ntw

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - ntw

  initializer:
    build: ./initializer
    image: aybjax-initializer
    container_name: aybjax-initializer
    environment:
      - NATS_URL=nats
      - NATS_PORT=4222
    depends_on:
      - nats
      - mongo
      - postgres
      - redis
    networks:
      - ntw

networks:
  ntw:
    driver: bridge

#   cache:
#     image: redis:6.2-alpine
#     restart: always
#     ports:
#       - '6379:6379'
#     # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#     command: redis-server --save 20 1 --loglevel warning
# #     volumes: 
# #       - cache:/data
# # volumes:
# #   cache:
# #     driver: local
#     networks:
#       - ntw
