apiVersion: v1
data:
  #  kongCredType: a2V5LWF1dGgK
  #  key: VDA5UVV5RWhJU0JHYjNWdVpDQnRaVG9wSUVrZ1FVMGdVRkpQVlVRZ1QwWWdXVTlWCg==
  kongCredType: a2V5LWF1dGg=
  #  key-auth
  key: VDA5UVV5RWhJU0JHYjNWdVpDQnRaVG9wSUVrZ1FVMGdVRkpQVlVRZ1QwWWdXVTlW
#  T09QUyEhISBGb3VuZCBtZTopIEkgQU0gUFJPVUQgT0YgWU9V
kind: Secret
metadata:
  name: aybjax-password
type: Opaque

#  kubectl create secret generic aybjax-password \
#  --from-literal=kongCredType=key-auth  \
#  --from-literal=key=T09QUyEhISBGb3VuZCBtZTopIEkgQU0gUFJPVUQgT0YgWU9V