apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: db
          # valueFrom:
          #   secretKeyRef:
          #     name: mongo-secret
          #     key: mongo-user
          # valueFrom:
          #   configMapKeyRef:
          #     name: mongo-config
          #     key: mongo-url


---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  # type: ClusterIP # default
  # type: NodePort
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      # nodePort: btw 30000-32767
