export REDIS_URL=localhost
export REDIS_PORT=6379
export NATS_URL=localhost
export NATS_PORT=4222
export POSTGRES_USER=user
export POSTGRES_PASSWORD=password
export MONGO_URL=localhost
export MONGO_PORT=27017
# export POSTGRES_DB=nis
export GRPC_STUDENT_URL=localhost
export GRPC_STUDENT_PORT=50051
